# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.

orbs:
  aws-cli: circleci/aws-cli@1.0.0

jobs:
  build_test:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Install MySQL
          command: |
            sudo apt-get update
            sudo apt-get install mysql-client
            mysql --version
            echo $MYSQLPW
            mysql -h oculadata-db1.ck24etdkkajl.us-east-1.rds.amazonaws.com -P 3306 -u admin --password=$MYSQLPW demo < db/exportdb.sql | awk '{printf "%s,%s,%s,%s,%s\n", $1, $2, $3, $4, $5}' > a.csv 
      - run:
          name: Build Demo
          command: |
            ls -la *
            aws s3 ls
    
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - build_test
